export const ORDERS_LIST_REQUEST = " ORDERS_LIST_REQUEST";
export const ORDERS_LIST_SUCCSESS = " ORDERS_LIST_SUCCSESS";
export const ORDERS_LIST_FAIL = " ORDERS_LIST_FAIL";

export const ORDER_STATUS_REQUEST = " ORDER_STATUS_REQUEST";
export const ORDER_STATUS_SUCCSESS = " ORDER_STATUS_SUCCSESS";
export const ORDER_STATUS_FAIL = "ORDER_STATUS_FAIL ";
export const ORDER_STATUS_RESET = "ORDER_STATUS_RESET ";
