export const CATEGORIES_LIST_REQUEST = " CATEGORIES_LIST_REQUEST";
export const CATEGORIES_LIST_SUCCSESS = " CATEGORIES_LIST_SUCCSESS";
export const CATEGORIES_LIST_FAIL = " CATEGORIES_LIST_FAIL";

export const CATEGORIES_UPDATE_REQUEST = " CATEGORIES_UPDATE_REQUEST";
export const CATEGORIES_UPDATE_SUCCSESS = " CATEGORIES_UPDATE_SUCCSESS";
export const CATEGORIES_UPDATE_FAIL = "CATEGORIES_UPDATE_FAIL ";
export const CATEGORIES_UPDATE_RESET = "CATEGORIES_UPDATE_RESET ";

export const CATEGORIES_ADD_REQUEST = " CATEGORIES_ADD_REQUEST";
export const CATEGORIES_ADD_SUCCSESS = " CATEGORIES_ADD_SUCCSESS";
export const CATEGORIES_ADD_FAIL = "CATEGORIES_ADD_FAIL ";
export const CATEGORIES_ADD_RESET = "CATEGORIES_ADD_RESET ";

export const CATEGORIES_DELETE_REQUEST = " CATEGORIES_DELETE_REQUEST";
export const CATEGORIES_DELETE_SUCCSESS = " CATEGORIES_DELETE_SUCCSESS";
export const CATEGORIES_DELETE_FAIL = "CATEGORIES_DELETE_FAIL ";
export const CATEGORIES_DELETE_RESET = "CATEGORIES_DELETE_RESET ";

