export const MANUFACTURER_LIST_REQUEST = "MANUFACTURER_LIST_REQUEST";
export const MANUFACTURER_LIST_SUCCSESS = "MANUFACTURER_LIST_SUCCSESS";
export const MANUFACTURER_LIST_FAIL = "MANUFACTURER_LIST_FAIL";

export const MANUFACTURER_ADD_REQUEST = "MANUFACTURER_ADD_REQUEST";
export const MANUFACTURER_ADD_SUCCSESS = "MANUFACTURER_ADD_SUCCSESS";
export const MANUFACTURER_ADD_FAIL = "MANUFACTURER_ADD_FAIL";
export const MANUFACTURER_ADD_RESET = "MANUFACTURER_ADD_RESET";


export const MANUFACTURER_DELETE_REQUEST = " MANUFACTURER_DELETE_REQUEST";
export const MANUFACTURER_DELETE_SUCCSESS = " MANUFACTURER_DELETE_SUCCSESS";
export const MANUFACTURER_DELETE_FAIL = "MANUFACTURER_DELETE_FAIL ";
export const MANUFACTURER_DELETE_RESET = "MANUFACTURER_DELETE_RESET ";

export const MANUFACTURER_UPDATE_REQUEST = "MANUFACTURER_UPDATE_REQUEST";
export const MANUFACTURER_UPDATE_SUCCSESS = "MANUFACTURER_UPDATE_SUCCSESS";
export const MANUFACTURER_UPDATE_FAIL = "MANUFACTURER_UPDATE_FAIL";
export const MANUFACTURER_UPDATE_RESET = "MANUFACTURER_UPDATE_RESET";
