export const PRODUCTS_LIST_REQUEST = " PRODUCTS_LIST_REQUEST";
export const PRODUCTS_LIST_SUCCSESS = " PRODUCTS_LIST_SUCCSESS";
export const PRODUCTS_LIST_FAIL = " PRODUCTS_LIST_FAIL";

export const PRODUCTS_UPDATE_REQUEST = " PRODUCTS_UPDATE_REQUEST";
export const PRODUCTS_UPDATE_SUCCSESS = " PRODUCTS_UPDATE_SUCCSESS";
export const PRODUCTS_UPDATE_FAIL = "PRODUCTS_UPDATE_FAIL ";
export const PRODUCTS_UPDATE_RESET = "PRODUCTS_UPDATE_RESET ";

export const PRODUCTS_ADD_REQUEST = " PRODUCTS_ADD_REQUEST";
export const PRODUCTS_ADD_SUCCSESS = " PRODUCTS_ADD_SUCCSESS";
export const PRODUCTS_ADD_FAIL = "PRODUCTS_ADD_FAIL ";
export const PRODUCTS_ADD_RESET = "PRODUCTS_ADD_RESET ";

export const PRODUCTS_DELETE_REQUEST = " PRODUCTS_DELETE_REQUEST";
export const PRODUCTS_DELETE_SUCCSESS = " PRODUCTS_DELETE_SUCCSESS";
export const PRODUCTS_DELETE_FAIL = "PRODUCTS_DELETE_FAIL ";
export const PRODUCTS_DELETE_RESET = "PRODUCTS_DELETE_RESET ";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAILS = "PRODUCT_DETAILS_FAILS";
export const PRODUCT_DETAILS_RESET = "PRODUCT_DETAILS_RESET";
