export const SUBCATEGORIES_LIST_REQUEST = " SUBCATEGORIES_LIST_REQUEST";
export const SUBCATEGORIES_LIST_SUCCSESS = " SUBCATEGORIES_LIST_SUCCSESS";
export const SUBCATEGORIES_LIST_FAIL = " SUBCATEGORIES_LIST_FAIL";

export const SUBCATEGORIES_UPDATE_REQUEST = " SUBCATEGORIES_UPDATE_REQUEST";
export const SUBCATEGORIES_UPDATE_SUCCSESS = " SUBCATEGORIES_UPDATE_SUCCSESS";
export const SUBCATEGORIES_UPDATE_FAIL = "SUBCATEGORIES_UPDATE_FAIL ";
export const SUBCATEGORIES_UPDATE_RESET = "SUBCATEGORIES_UPDATE_RESET ";

export const SUBCATEGORIES_ADD_REQUEST = " SUBCATEGORIES_ADD_REQUEST";
export const SUBCATEGORIES_ADD_SUCCSESS = " SUBCATEGORIES_ADD_SUCCSESS";
export const SUBCATEGORIES_ADD_FAIL = "SUBCATEGORIES_ADD_FAIL ";
export const SUBCATEGORIES_ADD_RESET = "SUBCATEGORIES_ADD_RESET ";

export const SUBCATEGORIES_DELETE_REQUEST = " SUBCATEGORIES_DELETE_REQUEST";
export const SUBCATEGORIES_DELETE_SUCCSESS = " SUBCATEGORIES_DELETE_SUCCSESS";
export const SUBCATEGORIES_DELETE_FAIL = "SUBCATEGORIES_DELETE_FAIL ";
export const SUBCATEGORIES_DELETE_RESET = "SUBCATEGORIES_DELETE_RESET ";