export const USERS_LIST_REQUEST = " USERS_LIST_REQUEST";
export const USERS_LIST_SUCCSESS = " USERS_LIST_SUCCSESS";
export const USERS_LIST_FAIL = " USERS_LIST_FAIL";

export const USERS_ROLE_UPDATE_REQUEST = " USERS_ROLE_UPDATE_REQUEST";
export const USERS_ROLE_UPDATE_SUCCSESS = " USERS_ROLE_UPDATE_SUCCSESS";
export const USERS_ROLE_UPDATE_FAIL = " USERS_ROLE_UPDATE_FAIL";
